# Generated by Django 5.0.3 on 2024-03-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_candidateprofile_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
    ]
