# Generated by Django 5.0.3 on 2024-03-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.CharField(max_length=20),
        ),
    ]
