# Generated by Django 5.0.3 on 2024-03-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employer_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
