# Generated by Django 5.0.3 on 2024-03-14 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_candidate_resume_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='contact_email',
            field=models.EmailField(default=datetime.datetime(2024, 3, 14, 15, 8, 38, 58492, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='contact_phone',
            field=models.CharField(default=datetime.datetime(2024, 3, 14, 15, 9, 58, 948486, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
