# Generated by Django 5.0.3 on 2024-03-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobapplication_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='candidate',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('contact_email', 'job')},
        ),
        migrations.AlterIndexTogether(
            name='jobapplication',
            index_together={('contact_email', 'job')},
        ),
    ]
